% You can also change ../lib for the correspoding install path
% MATLAB
if (ispc)
    mex -output bayesopt bayesoptmex.c ..\lib\Release\bayesopt.lib ...
        ..\lib\Release\nlopt.lib ...
        -I..\include -I..\wrappers -I..\nlopt\api 

   mex -output bayesoptdisc bayesoptdiscmex.c ../lib/Release/bayesopt.lib ...
        ../lib/Release/nlopt.lib -I../include -I../wrappers -I../nlopt/api 
else
    mex -output bayesopt bayesoptmex.c ../lib/bayesopt.so ../lib/libnlopt.so ...
        -I../include -I../wrappers -I../nlopt/api 

    mex -output bayesoptdisc bayesoptdiscmex.c ../lib/bayesopt.so ...
        ../lib/libnlopt.so -I../include -I../wrappers -I../nlopt/api 
end