% You can also change ../lib for the correspoding install path
% Octave
mkoctfile -L../lib -l:bayesopt.so -lnlopt -I../include -I../wrappers ...
    -I../nlopt/api --mex "-Wl,-rpath=../lib" --output bayesopt.mex ...
    bayesoptmex.c

mkoctfile -L../lib -l:bayesopt.so -lnlopt -I../include -I../wrappers ...
    -I../nlopt/api --mex "-Wl,-rpath=../lib" --output bayesoptdisc.mex ...
    bayesoptdiscmex.c

    
