var searchData=
[
  ['bayes_5foptimization',['bayes_optimization',['../group__BayesOpt.html#ga345c3b2560085efeb726610f4d914ce4',1,'bayes_optimization(int nDim, eval_func f, void *f_data, const double *lb, const double *ub, double *x, double *minf, bopt_params parameters):&#160;bayesoptwpr.cpp'],['../group__BayesOpt.html#ga345c3b2560085efeb726610f4d914ce4',1,'bayes_optimization(int nDim, eval_func f, void *f_data, const double *lb, const double *ub, double *x, double *minf, bopt_params parameters):&#160;bayesoptwpr.cpp']]],
  ['bayes_5foptimization_5fcategorical',['bayes_optimization_categorical',['../group__BayesOpt.html#ga968cfc4ace9f52705594c58e52f573de',1,'bayes_optimization_categorical(int nDim, eval_func f, void *f_data, int *categories, double *x, double *minf, bopt_params parameters):&#160;bayesoptwpr.cpp'],['../group__BayesOpt.html#ga968cfc4ace9f52705594c58e52f573de',1,'bayes_optimization_categorical(int nDim, eval_func f, void *f_data, int *categories, double *x, double *minf, bopt_params parameters):&#160;bayesoptwpr.cpp']]],
  ['bayes_5foptimization_5fdisc',['bayes_optimization_disc',['../group__BayesOpt.html#gac60ca43a9ad0bb102438dbffddd1e228',1,'bayes_optimization_disc(int nDim, eval_func f, void *f_data, double *valid_x, size_t n_points, double *x, double *minf, bopt_params parameters):&#160;bayesoptwpr.cpp'],['../group__BayesOpt.html#gac60ca43a9ad0bb102438dbffddd1e228',1,'bayes_optimization_disc(int nDim, eval_func f, void *f_data, double *valid_x, size_t n_points, double *x, double *minf, bopt_params parameters):&#160;bayesoptwpr.cpp']]],
  ['bayesopt',['bayesopt',['../namespacebayesopt.html',1,'bayesopt'],['../group__BayesOpt.html',1,'(Global Namespace)']]],
  ['bayesopt_2eh',['bayesopt.h',['../bayesopt_8h.html',1,'']]],
  ['bayesopt_2ehpp',['bayesopt.hpp',['../bayesopt_8hpp.html',1,'']]],
  ['bayesoptbase',['BayesOptBase',['../classbayesopt_1_1BayesOptBase.html',1,'bayesopt::BayesOptBase'],['../classbayesopt_1_1BayesOptBase.html#a708e7a69df95a8a5aa563e7a6a9694bf',1,'bayesopt::BayesOptBase::BayesOptBase()']]],
  ['bayesoptbase_2ehpp',['bayesoptbase.hpp',['../bayesoptbase_8hpp.html',1,'']]],
  ['bayesoptcategorical',['BayesOptCategorical',['../classbayesoptmodule_1_1BayesOptCategorical.html',1,'bayesoptmodule']]],
  ['bayesoptcontinuous',['BayesOptContinuous',['../classbayesoptmodule_1_1BayesOptContinuous.html',1,'bayesoptmodule']]],
  ['bayesoptdiscrete',['BayesOptDiscrete',['../classbayesoptmodule_1_1BayesOptDiscrete.html',1,'bayesoptmodule']]],
  ['bayesoptextras_2eh',['bayesoptextras.h',['../bayesoptextras_8h.html',1,'']]],
  ['bayesoptmodule_2epy',['bayesoptmodule.py',['../bayesoptmodule_8py.html',1,'']]],
  ['bayesoptprocess',['BayesOptProcess',['../classdemo__multiprocess_1_1BayesOptProcess.html',1,'demo_multiprocess']]],
  ['bayesoptpython',['BayesOptPython',['../group__BayesOptPython.html',1,'']]],
  ['bayesopttest',['BayesOptTest',['../classdemo__distance_1_1BayesOptTest.html',1,'demo_distance.BayesOptTest'],['../classdemo__quad_1_1BayesOptTest.html',1,'demo_quad.BayesOptTest']]],
  ['beta',['beta',['../structbopt__params.html#ad837157d49d6e1e1dfaec9071ed35d9a',1,'bopt_params::beta()'],['../classbayesopt_1_1Parameters.html#a106fcac4a05407be939b64db00e793af',1,'bayesopt::Parameters::beta()']]],
  ['biasedexpectedimprovement',['BiasedExpectedImprovement',['../classbayesopt_1_1BiasedExpectedImprovement.html',1,'bayesopt']]],
  ['bobyqa',['BOBYQA',['../namespacebayesopt.html#a6263ff983d7baa84c74f47737082a26ead50bd314b17d333edf9552a12b87a80d',1,'bayesopt']]],
  ['bopt_5fparams',['bopt_params',['../structbopt__params.html',1,'']]],
  ['bopt_5fstate_2ehpp',['bopt_state.hpp',['../bopt__state_8hpp.html',1,'']]],
  ['boptstate',['BOptState',['../classbayesopt_1_1BOptState.html',1,'bayesopt::BOptState'],['../classbayesopt_1_1BOptState.html#a68c7112d362953944bce42179cedff7a',1,'bayesopt::BOptState::BOptState()']]],
  ['bayesian_20optimization',['Bayesian optimization',['../bopttheory.html',1,'reference']]],
  ['boundingbox',['BoundingBox',['../classbayesopt_1_1utils_1_1BoundingBox.html',1,'bayesopt::utils']]],
  ['boundingbox_2ehpp',['boundingbox.hpp',['../boundingbox_8hpp.html',1,'']]],
  ['braninnormalized',['BraninNormalized',['../classBraninNormalized.html',1,'']]],
  ['bibliography',['Bibliography',['../citelist.html',1,'']]],
  ['bayesopt_3a_20a_20bayesian_20optimization_20library',['BayesOpt: A Bayesian optimization library',['../index.html',1,'']]],
  ['utils',['utils',['../namespacebayesopt_1_1utils.html',1,'bayesopt']]]
];
