var files =
[
    [ "ackley.m", "ackley_8m_source.html", null ],
    [ "bayesopt.h", "bayesopt_8h.html", "bayesopt_8h" ],
    [ "bayesopt.hpp", "bayesopt_8hpp.html", [
      [ "BoundingBox", "classbayesopt_1_1utils_1_1BoundingBox.html", "classbayesopt_1_1utils_1_1BoundingBox" ]
    ] ],
    [ "bayesoptbase.cpp", "bayesoptbase_8cpp_source.html", null ],
    [ "bayesoptbase.hpp", "bayesoptbase_8hpp.html", "bayesoptbase_8hpp" ],
    [ "bayesoptcatmex.c", "bayesoptcatmex_8c_source.html", null ],
    [ "bayesoptcont.cpp", "bayesoptcont_8cpp_source.html", null ],
    [ "bayesoptcont.m", "bayesoptcont_8m_source.html", null ],
    [ "bayesoptdisc.cpp", "bayesoptdisc_8cpp_source.html", null ],
    [ "bayesoptdisc.m", "bayesoptdisc_8m_source.html", null ],
    [ "bayesoptdiscmex.c", "bayesoptdiscmex_8c_source.html", null ],
    [ "bayesoptextras.h", "bayesoptextras_8h.html", "bayesoptextras_8h" ],
    [ "bayesoptmex.c", "bayesoptmex_8c_source.html", null ],
    [ "bayesoptmodule.py", "bayesoptmodule_8py.html", "bayesoptmodule_8py" ],
    [ "bayesoptwpr.cpp", "bayesoptwpr_8cpp_source.html", null ],
    [ "bo_branin.cpp", "bo__branin_8cpp_source.html", null ],
    [ "bo_branin_display.cpp", "bo__branin__display_8cpp_source.html", null ],
    [ "bo_branin_mcmc.cpp", "bo__branin__mcmc_8cpp_source.html", null ],
    [ "bo_branin_timed.cpp", "bo__branin__timed_8cpp_source.html", null ],
    [ "bo_camelback.cpp", "bo__camelback_8cpp_source.html", null ],
    [ "bo_compare.cpp", "bo__compare_8cpp_source.html", null ],
    [ "bo_cont.cpp", "bo__cont_8cpp_source.html", null ],
    [ "bo_disc.cpp", "bo__disc_8cpp_source.html", null ],
    [ "bo_display.cpp", "bo__display_8cpp_source.html", null ],
    [ "bo_hartmann.cpp", "bo__hartmann_8cpp_source.html", null ],
    [ "bo_oned.cpp", "bo__oned_8cpp_source.html", null ],
    [ "bopt_state.cpp", "bopt__state_8cpp_source.html", null ],
    [ "bopt_state.hpp", "bopt__state_8hpp.html", [
      [ "BOptState", "classbayesopt_1_1BOptState.html", "classbayesopt_1_1BOptState" ]
    ] ],
    [ "boundingbox.hpp", "boundingbox_8hpp.html", [
      [ "BoundingBox", "classbayesopt_1_1utils_1_1BoundingBox.html", "classbayesopt_1_1utils_1_1BoundingBox" ]
    ] ],
    [ "branin.m", "branin_8m_source.html", null ],
    [ "branin_system_calls.cpp", "branin__system__calls_8cpp_source.html", null ],
    [ "branin_xml.cpp", "branin__xml_8cpp_source.html", null ],
    [ "braninhighdim.m", "braninhighdim_8m_source.html", null ],
    [ "camelback.m", "camelback_8m_source.html", null ],
    [ "CMakeCCompilerId.c", "CMakeCCompilerId_8c_source.html", null ],
    [ "CMakeCXXCompilerId.cpp", "CMakeCXXCompilerId_8cpp_source.html", null ],
    [ "compile_matlab.m", "compile__matlab_8m_source.html", null ],
    [ "compile_octave.m", "compile__octave_8m_source.html", null ],
    [ "conditionalbayesprocess.cpp", "conditionalbayesprocess_8cpp_source.html", null ],
    [ "conditionalbayesprocess.hpp", "conditionalbayesprocess_8hpp.html", null ],
    [ "criteria_a_opt.hpp", "criteria__a__opt_8hpp.html", null ],
    [ "criteria_combined.hpp", "criteria__combined_8hpp.html", null ],
    [ "criteria_distance.hpp", "criteria__distance_8hpp.html", null ],
    [ "criteria_ei.hpp", "criteria__ei_8hpp.html", null ],
    [ "criteria_expected.hpp", "criteria__expected_8hpp.html", null ],
    [ "criteria_functors.cpp", "criteria__functors_8cpp_source.html", null ],
    [ "criteria_functors.hpp", "criteria__functors_8hpp.html", null ],
    [ "criteria_hedge.cpp", "criteria__hedge_8cpp_source.html", null ],
    [ "criteria_hedge.hpp", "criteria__hedge_8hpp.html", null ],
    [ "criteria_lcb.hpp", "criteria__lcb_8hpp.html", null ],
    [ "criteria_mi.hpp", "criteria__mi_8hpp_source.html", null ],
    [ "criteria_poi.hpp", "criteria__poi_8hpp.html", null ],
    [ "criteria_prod.hpp", "criteria__prod_8hpp.html", null ],
    [ "criteria_sum.hpp", "criteria__sum_8hpp.html", null ],
    [ "criteria_thompson.hpp", "criteria__thompson_8hpp.html", null ],
    [ "dataset.cpp", "dataset_8cpp_source.html", null ],
    [ "dataset.hpp", "dataset_8hpp.html", null ],
    [ "demo_cam.py", "demo__cam_8py_source.html", null ],
    [ "demo_dimscaling.py", "demo__dimscaling_8py_source.html", null ],
    [ "demo_distance.py", "demo__distance_8py_source.html", null ],
    [ "demo_multiprocess.py", "demo__multiprocess_8py_source.html", null ],
    [ "demo_quad.py", "demo__quad_8py_source.html", null ],
    [ "demo_rembo.m", "demo__rembo_8m_source.html", null ],
    [ "demo_test.m", "demo__test_8m_source.html", null ],
    [ "displaygp.cpp", "displaygp_8cpp_source.html", null ],
    [ "displaygp.hpp", "displaygp_8hpp.html", "displaygp_8hpp" ],
    [ "dll_stuff.h", "dll__stuff_8h_source.html", null ],
    [ "eval_branin.py", "eval__branin_8py_source.html", null ],
    [ "eval_branin_xml.py", "eval__branin__xml_8py_source.html", null ],
    [ "feature_tests.c", "feature__tests_8c_source.html", null ],
    [ "feature_tests.cxx", "feature__tests_8cxx_source.html", null ],
    [ "fileparser.cpp", "fileparser_8cpp_source.html", null ],
    [ "fileparser.hpp", "fileparser_8hpp.html", [
      [ "FileParser", "classbayesopt_1_1utils_1_1FileParser.html", "classbayesopt_1_1utils_1_1FileParser" ]
    ] ],
    [ "gauss_distribution.cpp", "gauss__distribution_8cpp_source.html", null ],
    [ "gauss_distribution.hpp", "gauss__distribution_8hpp.html", [
      [ "GaussianDistribution", "classbayesopt_1_1GaussianDistribution.html", "classbayesopt_1_1GaussianDistribution" ]
    ] ],
    [ "gaussian_process.cpp", "gaussian__process_8cpp_source.html", null ],
    [ "gaussian_process.hpp", "gaussian__process_8hpp.html", null ],
    [ "gaussian_process_hierarchical.cpp", "gaussian__process__hierarchical_8cpp_source.html", null ],
    [ "gaussian_process_hierarchical.hpp", "gaussian__process__hierarchical_8hpp.html", null ],
    [ "gaussian_process_ml.cpp", "gaussian__process__ml_8cpp_source.html", null ],
    [ "gaussian_process_ml.hpp", "gaussian__process__ml_8hpp.html", null ],
    [ "gaussian_process_normal.cpp", "gaussian__process__normal_8cpp_source.html", null ],
    [ "gaussian_process_normal.hpp", "gaussian__process__normal_8hpp.html", null ],
    [ "gpmlnlopt.m", "gpmlnlopt_8m_source.html", null ],
    [ "gpmltest.m", "gpmltest_8m_source.html", null ],
    [ "gridsampling.hpp", "gridsampling_8hpp.html", "gridsampling_8hpp" ],
    [ "hartmann.m", "hartmann_8m_source.html", null ],
    [ "indexvector.hpp", "indexvector_8hpp.html", "indexvector_8hpp" ],
    [ "inneroptimization.cpp", "inneroptimization_8cpp_source.html", null ],
    [ "inneroptimization.hpp", "inneroptimization_8hpp.html", "inneroptimization_8hpp" ],
    [ "kernel_atomic.hpp", "kernel__atomic_8hpp.html", null ],
    [ "kernel_combined.hpp", "kernel__combined_8hpp.html", null ],
    [ "kernel_const.hpp", "kernel__const_8hpp_source.html", null ],
    [ "kernel_functors.cpp", "kernel__functors_8cpp_source.html", null ],
    [ "kernel_functors.hpp", "kernel__functors_8hpp.html", "kernel__functors_8hpp" ],
    [ "kernel_gaussian.hpp", "kernel__gaussian_8hpp_source.html", null ],
    [ "kernel_hamming.hpp", "kernel__hamming_8hpp_source.html", null ],
    [ "kernel_linear.hpp", "kernel__linear_8hpp_source.html", null ],
    [ "kernel_matern.hpp", "kernel__matern_8hpp_source.html", null ],
    [ "kernel_polynomial.hpp", "kernel__polynomial_8hpp_source.html", null ],
    [ "kernel_prod.hpp", "kernel__prod_8hpp_source.html", null ],
    [ "kernel_rq.hpp", "kernel__rq_8hpp_source.html", null ],
    [ "kernel_sum.hpp", "kernel__sum_8hpp_source.html", null ],
    [ "kernelregressor.cpp", "kernelregressor_8cpp_source.html", null ],
    [ "kernelregressor.hpp", "kernelregressor_8hpp.html", null ],
    [ "langermann.m", "langermann_8m_source.html", null ],
    [ "lhs.hpp", "lhs_8hpp.html", "lhs_8hpp" ],
    [ "log.hpp", "log_8hpp.html", "log_8hpp" ],
    [ "mcmc_sampler.cpp", "mcmc__sampler_8cpp_source.html", null ],
    [ "mcmc_sampler.hpp", "mcmc__sampler_8hpp.html", "mcmc__sampler_8hpp" ],
    [ "mean_atomic.hpp", "mean__atomic_8hpp.html", null ],
    [ "mean_combined.hpp", "mean__combined_8hpp.html", null ],
    [ "mean_functors.cpp", "mean__functors_8cpp_source.html", null ],
    [ "mean_functors.hpp", "mean__functors_8hpp.html", "mean__functors_8hpp" ],
    [ "michalewicz.m", "michalewicz_8m_source.html", null ],
    [ "nei.m", "nei_8m_source.html", null ],
    [ "neinlopt.m", "neinlopt_8m_source.html", null ],
    [ "nonparametricprocess.cpp", "nonparametricprocess_8cpp_source.html", null ],
    [ "nonparametricprocess.hpp", "nonparametricprocess_8hpp.html", null ],
    [ "optimizable.hpp", "optimizable_8hpp.html", [
      [ "RBOptimizable", "classbayesopt_1_1RBOptimizable.html", "classbayesopt_1_1RBOptimizable" ],
      [ "RGBOptimizable", "classbayesopt_1_1RGBOptimizable.html", "classbayesopt_1_1RGBOptimizable" ],
      [ "RBOptimizableWrapper", "classbayesopt_1_1RBOptimizableWrapper.html", "classbayesopt_1_1RBOptimizableWrapper" ],
      [ "RGBOptimizableWrapper", "classbayesopt_1_1RGBOptimizableWrapper.html", "classbayesopt_1_1RGBOptimizableWrapper" ]
    ] ],
    [ "param_loader.cpp", "param__loader_8cpp_source.html", null ],
    [ "param_loader.hpp", "param__loader_8hpp.html", [
      [ "ParamLoader", "classbayesopt_1_1utils_1_1ParamLoader.html", "classbayesopt_1_1utils_1_1ParamLoader" ]
    ] ],
    [ "parameters.cpp", "parameters_8cpp_source.html", null ],
    [ "parameters.h", "parameters_8h.html", "parameters_8h" ],
    [ "parameters.hpp", "parameters_8hpp.html", "parameters_8hpp" ],
    [ "parser.cpp", "parser_8cpp_source.html", null ],
    [ "parser.hpp", "parser_8hpp.html", "parser_8hpp" ],
    [ "posterior_empirical.cpp", "posterior__empirical_8cpp_source.html", null ],
    [ "posterior_empirical.hpp", "posterior__empirical_8hpp_source.html", null ],
    [ "posterior_fixed.cpp", "posterior__fixed_8cpp_source.html", null ],
    [ "posterior_fixed.hpp", "posterior__fixed_8hpp.html", null ],
    [ "posterior_mcmc.cpp", "posterior__mcmc_8cpp_source.html", null ],
    [ "posterior_mcmc.hpp", "posterior__mcmc_8hpp.html", [
      [ "MCMCModel", "classbayesopt_1_1MCMCModel.html", "classbayesopt_1_1MCMCModel" ]
    ] ],
    [ "posteriormodel.cpp", "posteriormodel_8cpp_source.html", null ],
    [ "posteriormodel.hpp", "posteriormodel_8hpp.html", null ],
    [ "prob_distribution.hpp", "prob__distribution_8hpp.html", [
      [ "ProbabilityDistribution", "classbayesopt_1_1ProbabilityDistribution.html", "classbayesopt_1_1ProbabilityDistribution" ]
    ] ],
    [ "quadratic.m", "quadratic_8m_source.html", null ],
    [ "randgen.hpp", "randgen_8hpp.html", "randgen_8hpp" ],
    [ "readlog.m", "readlog_8m_source.html", null ],
    [ "rosenbrock.m", "rosenbrock_8m_source.html", null ],
    [ "specialtypes.hpp", "specialtypes_8hpp.html", "specialtypes_8hpp" ],
    [ "student_t_distribution.cpp", "student__t__distribution_8cpp_source.html", null ],
    [ "student_t_distribution.hpp", "student__t__distribution_8hpp.html", [
      [ "StudentTDistribution", "classbayesopt_1_1StudentTDistribution.html", "classbayesopt_1_1StudentTDistribution" ]
    ] ],
    [ "student_t_process_jef.cpp", "student__t__process__jef_8cpp_source.html", null ],
    [ "student_t_process_jef.hpp", "student__t__process__jef_8hpp.html", null ],
    [ "student_t_process_nig.cpp", "student__t__process__nig_8cpp_source.html", null ],
    [ "student_t_process_nig.hpp", "student__t__process__nig_8hpp.html", null ],
    [ "testfunctions.hpp", "testfunctions_8hpp_source.html", null ],
    [ "ublas_cholesky.hpp", "ublas__cholesky_8hpp.html", "ublas__cholesky_8hpp" ],
    [ "ublas_elementwise.hpp", "ublas__elementwise_8hpp.html", "ublas__elementwise_8hpp" ],
    [ "ublas_extra.cpp", "ublas__extra_8cpp_source.html", null ],
    [ "ublas_extra.hpp", "ublas__extra_8hpp.html", "ublas__extra_8hpp" ],
    [ "ublas_trace.hpp", "ublas__trace_8hpp_source.html", null ]
];