BayesOpt: NonParametricProcesses
NonParametricProcesses
Set of nonparametric processes (Gaussian process, Student's t process, etc.) for surrogate modelling.
Classes
class bayesopt::ConditionalBayesProcess
Empirical Bayesian NonParametric process.
class bayesopt::Dataset
Dataset model to deal with the vector (real) based datasets.
class bayesopt::GaussianProcess
Standard zero mean gaussian process with noisy observations.
class bayesopt::HierarchicalGaussianProcess
Virtual class for hierarchical Gaussian processes.
class bayesopt::GaussianProcessML
Gaussian process with ML parameters.
class bayesopt::GaussianProcessNormal
Gaussian process with normal prior on the parameters.
class bayesopt::KernelRegressor
Abstract class to implement non-parametric processes.
class bayesopt::NonParametricProcess
Abstract class to implement Bayesian regressors.
class bayesopt::StudentTProcessJeffreys
Student T process with Jeffreys prior.
class bayesopt::StudentTProcessNIG
Student's t process with Normal Inverse-Gamma hyperprior on mean and snigal variance parameters.
Functions
double bayesopt::ConditionalBayesProcess::evaluate (const vectord &x)
Computes the score (eg:likelihood) of the kernel parameters.
void bayesopt::Dataset::addSample (const vectord &x, double y)
double bayesopt::Dataset::getSampleY (size_t index) const
vectord bayesopt::Dataset::getSampleX (size_t index) const
double bayesopt::Dataset::getLastSampleY () const
vectord bayesopt::Dataset::getLastSampleX () const
vectord bayesopt::Dataset::getPointAtMinimum () const
double bayesopt::Dataset::getValueAtMinimum () const
size_t bayesopt::Dataset::getNSamples () const
void bayesopt::Dataset::updateMinMax (size_t i)
void bayesopt::KernelRegressor::fitSurrogateModel ()
Computes the initial surrogate model and updates the kernel parameters estimation.
size_t bayesopt::KernelRegressor::nHyperParameters ()
vectord bayesopt::KernelRegressor::getHyperParameters ()
void bayesopt::KernelRegressor::setHyperParameters (const vectord &theta)
void bayesopt::KernelRegressor::computeCorrMatrix (matrixd &corrMatrix)
Computes the Correlation (Kernel or Gram) matrix.
matrixd bayesopt::KernelRegressor::computeCorrMatrix ()
Computes the Correlation (Kernel or Gram) matrix.
vectord bayesopt::KernelRegressor::computeCrossCorrelation (const vectord &query)
double bayesopt::KernelRegressor::computeSelfCorrelation (const vectord &query)
void bayesopt::KernelRegressor::addNewPointToCholesky (const vectord &correlation, double selfcorrelation)
Adds a new point to the Cholesky decomposition of the Correlation matrix.
double bayesopt::NonParametricProcess::getValueAtMinimum ()
const Dataset * bayesopt::NonParametricProcess::getData ()
double bayesopt::NonParametricProcess::getSignalVariance ()
Detailed Description
Set of nonparametric processes (Gaussian process, Student's t process, etc.) for surrogate modelling.
Function Documentation
addNewPointToCholesky()
void bayesopt::KernelRegressor::addNewPointToCholesky (const vectord & correlation, double selfcorrelation) inline private
Adds a new point to the Cholesky decomposition of the Correlation matrix.
Definition at line 206 of file kernelregressor.hpp.
References bayesopt::utils::cholesky_add_row(), and bayesopt::KernelRegressor::mL.
evaluate()
double bayesopt::ConditionalBayesProcess::evaluate (const vectord & x) inline virtual
Computes the score (eg:likelihood) of the kernel parameters.
Warning: To evaluate the score, it is necessary to change the parameters
Parameters
x set of parameters.
Returns
score
Implements bayesopt::RBOptimizable.
Definition at line 105 of file conditionalbayesprocess.hpp.
References bayesopt::ConditionalBayesProcess::evaluateKernelParams().
fitSurrogateModel()
void bayesopt::KernelRegressor::fitSurrogateModel () inline virtual
Computes the initial surrogate model and updates the kernel parameters estimation.
This function requires to recompute the full Kernel matrix (and its decomposition). Use it with precaution.
Implements bayesopt::NonParametricProcess.
Definition at line 121 of file kernelregressor.hpp.
References bayesopt::KernelRegressor::computeCholeskyCorrelation(), bayesopt::NonParametricProcess::mSigma, and bayesopt::KernelRegressor::precomputePrediction().