BayesOpt: bayesopt::StudentTDistribution Class Reference
bayesopt::StudentTDistribution Class Reference
Public Member Functions
StudentTDistribution (randEngine &eng)
void setMeanAndStd (double mean, double std)
Sets the mean and std of the distribution.
void setDof (size_t dof)
Sets the degrees of freedom (dof) the distribution.
double pdf (double x)
Probability density function.
double negativeExpectedImprovement (double min, size_t g)
Expected Improvement algorithm for minimization.
double lowerConfidenceBound (double beta)
Lower confindence bound.
double negativeProbabilityOfImprovement (double min, double epsilon)
Probability of improvement algorithm for minimization.
double sample_query ()
Sample outcome acording to the marginal distribution at the query point.
double getMean ()
double getStd ()
Public Member Functions inherited from bayesopt::ProbabilityDistribution
ProbabilityDistribution (randEngine &eng)
Private Attributes
boost::math::students_t d_
double mean_
double std_
size_t dof_
Additional Inherited Members
Protected Attributes inherited from bayesopt::ProbabilityDistribution
randEngine & mtRandom
Detailed Description
Definition at line 36 of file student_t_distribution.hpp.
Member Function Documentation
lowerConfidenceBound()
double bayesopt::StudentTDistribution::lowerConfidenceBound (double beta) virtual
Lower confindence bound.
Can be seen as the inverse of the Upper confidence bound
Parameters
beta std coefficient (used for annealing)
Returns
value of the lower confidence bound
Implements bayesopt::ProbabilityDistribution.
Definition at line 28 of file student_t_distribution.cpp.
Referenced by pdf().
negativeExpectedImprovement()
double bayesopt::StudentTDistribution::negativeExpectedImprovement (double min, size_t g) virtual
Expected Improvement algorithm for minimization.
Parameters
min minimum value found
g exponent (used for annealing)
Returns
negative value of the expected improvement
Implements bayesopt::ProbabilityDistribution.
Definition at line 16 of file student_t_distribution.cpp.
Referenced by pdf().
negativeProbabilityOfImprovement()
double bayesopt::StudentTDistribution::negativeProbabilityOfImprovement (double min, double epsilon) virtual
Probability of improvement algorithm for minimization.
Parameters
min minimum value found
epsilon minimum improvement margin
Returns
negative value of the probability of improvement
Implements bayesopt::ProbabilityDistribution.
Definition at line 33 of file student_t_distribution.cpp.
Referenced by pdf().
pdf()
double bayesopt::StudentTDistribution::pdf (double x) inline virtual
Probability density function.
Parameters
x query point
Returns
probability
Implements bayesopt::ProbabilityDistribution.
Definition at line 63 of file student_t_distribution.hpp.
References lowerConfidenceBound(), negativeExpectedImprovement(), negativeProbabilityOfImprovement(), and sample_query().
sample_query()
double bayesopt::StudentTDistribution::sample_query () virtual
Sample outcome acording to the marginal distribution at the query point.
Returns
outcome
Implements bayesopt::ProbabilityDistribution.
Definition at line 40 of file student_t_distribution.cpp.
Referenced by pdf().
The documentation for this class was generated from the following files:
student_t_distribution.hpp
student_t_distribution.cpp